// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfxQhwL2LzjjgS01INCx_3iFFuiysZi5o',
    appId: '1:555430726038:web:cf0d27195053925253f5b7',
    messagingSenderId: '555430726038',
    projectId: 'voxxie-c3927',
    authDomain: 'voxxie-c3927.firebaseapp.com',
    storageBucket: 'voxxie-c3927.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs2OuL_KdsJkRlVAyPKdiJv6aLLBlWkDw',
    appId: '1:555430726038:android:1895dfa10bec7f5c53f5b7',
    messagingSenderId: '555430726038',
    projectId: 'voxxie-c3927',
    storageBucket: 'voxxie-c3927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCduqSzTCLmeIz_wbm9Tz4JabH0VAu5Px8',
    appId: '1:555430726038:ios:9213b47ce5a818ad53f5b7',
    messagingSenderId: '555430726038',
    projectId: 'voxxie-c3927',
    storageBucket: 'voxxie-c3927.appspot.com',
    iosBundleId: 'com.example.voxxie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCduqSzTCLmeIz_wbm9Tz4JabH0VAu5Px8',
    appId: '1:555430726038:ios:b410b2454ef4e58653f5b7',
    messagingSenderId: '555430726038',
    projectId: 'voxxie-c3927',
    storageBucket: 'voxxie-c3927.appspot.com',
    iosBundleId: 'com.example.voxxie.RunnerTests',
  );
}
